Add contributing
trapd00r/LS_COLORS pull request #167
Opened 2020-10-07 11:20 UTC by ArturBa

2020-10-07 12:36 UTC, ArturBa commented
Do you mind adding hacktoberfest badge on this? ;)

2020-10-09 03:01 UTC, rpdelaney commented
Thank you for this.

It would be nice if the one test actually worked. Maybe this will light a fire for me to fix that.

cc @trapd00r Japh I'd like your feedback on this, especially re: the code of conduct this adds, if you have the time

2020-10-09 03:51 UTC, trapd00r commented
> cc @trapd00r Japh I'd like your feedback on this, especially re: the code of conduct this adds, if you have the time

Hm. Do we really need a CoC? Who wrote it up? Standard boiler?

2020-10-09 19:40 UTC, rpdelaney commented
> Do we really need a CoC? 

We probably don't _need_ one. I'm not exactly _against_ it though. Unfortunately I wasn't as specific as I should have been in #109 about what I had in mind.

> Who wrote it up?

Good question. @ArturBa ?

2020-10-09 20:11 UTC, ArturBa commented
I've used some of a CoC template and adjust it to a project

2020-10-28 19:15 UTC, rpdelaney commented on CONTRIBUTING.md
> +1. Add file extension and its color to [`LS_COLORS`](./LS_COLORS)
```suggestion
1. Add the new file extension and its color to [`LS_COLORS`](./LS_COLORS). Try to find the most appropriate category for the file type and match the style to the others in the same category.
```

2020-10-28 19:17 UTC, rpdelaney requested changes
I appreciate this. A CONTRIBUTING file is the logical place for this stuff. I think we don't need a full code of conduct just yet. Please remove it and I will be happy to merge this in. Thanks!

2020-11-01 21:32 UTC, merged

2020-11-01 21:32 UTC, rpdelaney commented
Thank you!